import Head from "next/head";
import Image from "next/image";
import Collection from "../components/Collection";
import Explore from "../components/Explore";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Trending from "../components/Trending";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>opensea</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/c6.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"/>
      </Head>
      <div className="grad h-[50vh] px-[2rem]">
        <div className="">
          <Navbar />
          <Explore />
          <Trending />
          <Collection />
          <Footer />
        </div>
      </div>
    </div>
  );
}
